using app.Class;

Nain Durin = new Nain("Durin", 15, 6, true);
Elfe Elrond = new Elfe("Elrond", 15, 6, Durin);

Duel DurinVsElrond = new Duel(new Tuple<Guerrier, Guerrier>(Durin, Elrond), 5);
Console.WriteLine(DurinVsElrond.Duelists.Item1.GetLifePoints());
Console.WriteLine(DurinVsElrond.Duelists.Item2.GetLifePoints());
DurinVsElrond.StartManche(new Tuple<int, int>(1, 0));
Console.WriteLine(DurinVsElrond.Duelists.Item1.GetLifePoints());
Console.WriteLine(DurinVsElrond.Duelists.Item2.GetLifePoints());
Console.WriteLine("Démontage en régle");
DurinVsElrond.StartManche(new Tuple<int, int>(1, 0));
Console.WriteLine(DurinVsElrond.Duelists.Item1.GetLifePoints());
Console.WriteLine(DurinVsElrond.Duelists.Item2.GetLifePoints());
Console.WriteLine("Démontage en régle");
DurinVsElrond.StartManche(new Tuple<int, int>(1, 0));
Console.WriteLine(DurinVsElrond.Duelists.Item1.GetLifePoints());
Console.WriteLine(DurinVsElrond.Duelists.Item2.GetLifePoints());
Console.WriteLine("Démontage en régle");
DurinVsElrond.StartManche(new Tuple<int, int>(1, 0));
Console.WriteLine(DurinVsElrond.Duelists.Item1.GetLifePoints());
Console.WriteLine(DurinVsElrond.Duelists.Item2.GetLifePoints());
Console.WriteLine("Démontage en régle");
DurinVsElrond.StartManche(new Tuple<int, int>(1, 0));
Console.WriteLine(DurinVsElrond.Duelists.Item1.GetLifePoints());
Console.WriteLine(DurinVsElrond.Duelists.Item2.GetLifePoints());
Console.WriteLine("Démontage en régle");
DurinVsElrond.StartManche(new Tuple<int, int>(1, 0));
Console.WriteLine(DurinVsElrond.Duelists.Item1.GetLifePoints());
Console.WriteLine(DurinVsElrond.Duelists.Item2.GetLifePoints());
Console.WriteLine("Démontage en régle");
DurinVsElrond.StartManche(new Tuple<int, int>(1, 0));
Console.WriteLine(DurinVsElrond.Duelists.Item1.GetLifePoints());
Console.WriteLine(DurinVsElrond.Duelists.Item2.GetLifePoints());
Console.WriteLine("Démontage en régle");
DurinVsElrond.StartManche(new Tuple<int, int>(1, 0));
Console.WriteLine(DurinVsElrond.Duelists.Item1.GetLifePoints());
Console.WriteLine(DurinVsElrond.Duelists.Item2.GetLifePoints());
Console.WriteLine("Démontage en régle");
DurinVsElrond.StartManche(new Tuple<int, int>(1, 0));
Console.WriteLine(DurinVsElrond.Duelists.Item1.GetLifePoints());
Console.WriteLine(DurinVsElrond.Duelists.Item2.GetLifePoints());
Console.WriteLine("Démontage en régle");
DurinVsElrond.StartManche(new Tuple<int, int>(1, 0));
Console.WriteLine(DurinVsElrond.Duelists.Item1.GetLifePoints());
Console.WriteLine(DurinVsElrond.Duelists.Item2.GetLifePoints());
Console.WriteLine("Démontage en régle");
DurinVsElrond.StartManche(new Tuple<int, int>(1, 0));
Console.WriteLine(DurinVsElrond.Duelists.Item1.GetLifePoints());
Console.WriteLine(DurinVsElrond.Duelists.Item2.GetLifePoints());
Console.WriteLine("Démontage en régle");
DurinVsElrond.StartManche(new Tuple<int, int>(1, 0));
Console.WriteLine(DurinVsElrond.Duelists.Item1.GetLifePoints());
Console.WriteLine(DurinVsElrond.Duelists.Item2.GetLifePoints());
Console.WriteLine("Démontage en régle");
DurinVsElrond.StartManche(new Tuple<int, int>(1, 0));
Console.WriteLine(DurinVsElrond.Duelists.Item1.GetLifePoints());
Console.WriteLine(DurinVsElrond.Duelists.Item2.GetLifePoints());
Console.WriteLine("Démontage en régle");
DurinVsElrond.StartManche(new Tuple<int, int>(1, 0));
Console.WriteLine(DurinVsElrond.Duelists.Item1.GetLifePoints());
Console.WriteLine(DurinVsElrond.Duelists.Item2.GetLifePoints());
Console.WriteLine("Démontage en régle");
DurinVsElrond.StartManche(new Tuple<int, int>(1, 0));
Console.WriteLine(DurinVsElrond.Duelists.Item1.GetLifePoints());
Console.WriteLine(DurinVsElrond.Duelists.Item2.GetLifePoints());